const GAME_DATA = {
    subRealms: {
        1: { name: "Inicial", multiplier: 1.0 },
        2: { name: "Intermediário", multiplier: 1.25 },
        3: { name: "Avançado", multiplier: 1.6 },
        4: { name: "Pico", multiplier: 2.1 }
    },
    realms: {
        1: { name: "Temperar o Corpo", qiCap: 2000, multiplier: 1, tribulationDps: 80, tribulationYears: 2, karmaReward: 0, desc: "Seus ossos doem, mas sua vontade finalmente aprendeu a ranger junto." },
        2: { name: "Condensação de Qi", qiCap: 120000, multiplier: 5, tribulationDps: 3000, tribulationYears: 18, karmaReward: 1, desc: "O mundo deixa de ser ar e passa a ser alimento." },
        3: { name: "Estabelecimento de Fundação", qiCap: 2500000, multiplier: 25, tribulationDps: 800000, tribulationYears: 45, karmaReward: 2, desc: "Seu Dao deixa de ser rumor e ganha espinha dorsal." },
        4: { name: "Formação do Núcleo", qiCap: 40000000, multiplier: 125, tribulationDps: 250000000, tribulationYears: 90, karmaReward: 4, desc: "Uma estrela pessoal gira no seu dantian, pequena e tirânica." },
        5: { name: "Alma Nascente", qiCap: 800000000, multiplier: 625, tribulationDps: 2e11, tribulationYears: 180, karmaReward: 7, desc: "Sua alma aprende a andar antes mesmo de abandonar o corpo." },
        6: { name: "Separação Espiritual", qiCap: 15000000000, multiplier: 3125, tribulationDps: 2e15, tribulationYears: 360, karmaReward: 11, desc: "A carne já não manda tanto quanto antes." },
        7: { name: "Imortal Verdadeiro", qiCap: 250000000000, multiplier: 15625, tribulationDps: 2e19, tribulationYears: 720, karmaReward: 16, desc: "Os mortais juram que você sempre existiu." }
    },
    techniques: {
        click_base: {
            id: "click_base",
            name: "Técnica do Dedo Dourado",
            type: "click",
            baseCost: 10,
            costGrowth: 1.15,
            basePower: 1,
            desc: "Aumenta o Qi gerado por clique."
        }
    },
    buildings: {
        herbs: {
            id: "herbs",
            name: "Erva Espiritual",
            baseCost: 30,
            costGrowth: 1.14,
            desc: "Raízes úmidas de energia. Cada unidade gera 3 Qi/s.",
            generate: "qi",
            amount: 3
        },
        pills: {
            id: "pills",
            name: "Pílula da Fundação",
            baseCost: 1200,
            costGrowth: 1.18,
            desc: "Cada pílula aumenta a eficiência das Ervas em +1.5%.",
            generate: "herbs_mult",
            amount: 0.015
        },
        disciples: {
            id: "disciples",
            name: "Discípulo Exterior",
            baseCost: 15000,
            costGrowth: 1.22,
            desc: "Cada Discípulo gera 0.6 Pílula por segundo.",
            generate: "pills",
            amount: 0.6
        },
        elders: {
            id: "elders",
            name: "Ancião da Seita",
            baseCost: 500000,
            costGrowth: 1.27,
            desc: "Cada Ancião recruta 0.5 Discípulo por segundo.",
            generate: "disciples",
            amount: 0.5
        },
        arrays: {
            id: "arrays",
            name: "Matriz de Convergência",
            baseCost: 15000000,
            costGrowth: 1.32,
            desc: "Cada Matriz atrai 0.35 Ancião por segundo.",
            generate: "elders",
            amount: 0.35
        }
    },
    metaUpgrades: {
        dao_karma_gain: {
            id: "dao_karma_gain",
            name: "Compreensão do Samsara",
            baseCost: 1,
            costGrowth: 1.5,
            desc: "Aumenta o ganho de Karma ao reencarnar em +10%.",
            path: "man"
        },
        dao_cost_reduction: {
            id: "dao_cost_reduction",
            name: "Mente Vazia",
            baseCost: 2,
            costGrowth: 1.8,
            desc: "Reduz o crescimento de custo das propriedades.",
            path: "man"
        },
        dao_realm_mult: {
            id: "dao_realm_mult",
            name: "Ecos do Passado",
            baseCost: 5,
            costGrowth: 3,
            desc: "Multiplicadores de reino ganham um bônus massivo.",
            path: "man"
        },
        dao_life: {
            id: "dao_life",
            name: "Corpo de Tartaruga",
            baseCost: 1,
            costGrowth: 1.5,
            desc: "Aumenta a expectativa de vida inicial em +20 anos.",
            path: "heaven"
        },
        dao_offline: {
            id: "dao_offline",
            name: "Respiração Profunda",
            baseCost: 2,
            costGrowth: 2,
            desc: "Aumenta Qi manual e passivo em +10%.",
            path: "heaven"
        },
        dao_retain: {
            id: "dao_retain",
            name: "Memória da Alma",
            baseCost: 10,
            costGrowth: 5,
            desc: "Mantém 5% do Qi total na próxima vida.",
            path: "heaven"
        },
        dao_herb_mult: {
            id: "dao_herb_mult",
            name: "Solo Fértil",
            baseCost: 1,
            costGrowth: 1.5,
            desc: "Ervas geram 2x mais Qi.",
            path: "earth"
        },
        dao_pill_mult: {
            id: "dao_pill_mult",
            name: "Fogo Alquímico",
            baseCost: 3,
            costGrowth: 2,
            desc: "Pílulas são 50% mais eficientes ao buffar Ervas.",
            path: "earth"
        }
    },
    journeyActions: {
        work_farm: {
            id: "work_farm",
            name: "Trabalhar na Fazenda",
            desc: "Você ara a terra, fortalece os braços e compra mais alguns anos de humildade.",
            time_cost: 2,
            type: "corpo",
            requirements: {},
            effects: { body: 1 },
            unlocks: ["explore_forest", "explore_ruins"],
            repeatable: true,
            log: "Você volta da plantação com as mãos rachadas e o corpo um pouco mais firme."
        },
        hear_legends: {
            id: "hear_legends",
            name: "Ouvir Lendas na Taverna",
            desc: "Velhos bêbados mentem mal, mas mentem sobre imortais. Isso já basta.",
            time_cost: 2,
            type: "social",
            requirements: {},
            effects: { mind: 2 },
            unlocks: ["breathe"],
            repeatable: false,
            log: "As histórias plantam ambição onde antes só havia cansaço."
        },
        village_elder: {
            id: "village_elder",
            name: "Consultar o Ancião da Vila",
            desc: "O velho sabe pouco, mas sabe apontar para as montanhas certas.",
            time_cost: 2,
            type: "social",
            requirements: {},
            effects: { body: 1, mind: 1 },
            unlocks: ["sect_recruiter", "find_cave"],
            repeatable: false,
            log: "O ancião fala sobre cavernas, seitas e o tipo de loucura que vale a pena perseguir."
        },
        rest_under_tree: {
            id: "rest_under_tree",
            name: "Descansar sob a Árvore Antiga",
            desc: "Você silencia a respiração e escuta o vento tentando ensinar alguma coisa.",
            time_cost: 2,
            type: "cultivo",
            requirements: {},
            effects: { mind: 1, qi: 10 },
            unlocks: ["breathe"],
            repeatable: true,
            log: "Nada aconteceu de grandioso. Ainda assim, seu coração ficou mais quieto."
        },
        breathe: {
            id: "breathe",
            name: "Tentar Sentir o Qi",
            desc: "Você tenta respirar o mundo sem parecer ridículo.",
            time_cost: 3,
            type: "cultivo",
            requirements: { mind: 12 },
            effects: { qi: 60, mind: 1 },
            unlock_flags: ["canMeditate"],
            unlocks: ["read_scroll", "watch_stars"],
            repeatable: false,
            ui_reward_summary: "Desbloqueia meditação e inicia seu primeiro fluxo passivo de Qi.",
            log: "Uma corrente morna passa pelos seus meridianos. Meditar deixou de ser superstição."
        },
        find_cave: {
            id: "find_cave",
            name: "Investigar a Caverna Brilhante",
            desc: "Uma caverna húmida exala energia verde. Isso parece promissor e levemente insalubre.",
            time_cost: 3,
            type: "cultivo",
            requirements: { qi: 80 },
            effects: { qi: 120, mind: 1 },
            unlock_flags: ["canBuyHerbs"],
            unlocks: ["gather_spirit_herbs", "read_scroll"],
            repeatable: false,
            ui_reward_summary: "Desbloqueia Ervas Espirituais e abre a primeira layer comprável do idle.",
            log: "Você encontra ervas espirituais e um abrigo bom o bastante para sonhar com grandeza."
        },
        explore_forest: {
            id: "explore_forest",
            name: "Explorar a Floresta Sombria",
            desc: "A mata cobra coragem de entrada e sangue na saída.",
            time_cost: 3,
            type: "risco",
            requirements: { body: 11 },
            effects: { body: 2 },
            unlocks: ["hunt_wild_boar"],
            repeatable: false,
            log: "Você volta arranhado, vivo e um pouco menos impressionável."
        },
        explore_ruins: {
            id: "explore_ruins",
            name: "Explorar Ruínas Abandonadas",
            desc: "Pedras quebradas, estelas rachadas e um cheiro de sorte errada.",
            time_cost: 3,
            type: "risco",
            requirements: { mind: 11 },
            effects: { mind: 1, karma: -1 },
            unlocks: ["forbidden_whisper"],
            repeatable: false,
            log: "Nas ruínas, algo antigo percebe que você é tolo o bastante para continuar."
        },
        read_scroll: {
            id: "read_scroll",
            name: "Ler Pergaminhos Antigos",
            desc: "Os caracteres são ruins, mas a compreensão melhora com repetição.",
            time_cost: 3,
            type: "social",
            requirements: { mind: 13 },
            effects: { mind: 1 },
            unlocks: ["study_alchemy"],
            repeatable: true,
            log: "Cada linha lida arranca um pouco de ignorância da sua testa."
        },
        gather_spirit_herbs: {
            id: "gather_spirit_herbs",
            name: "Coletar Ervas Espirituais",
            desc: "Você aprende a colher sem destruir a raiz, o campo ou a própria mão.",
            time_cost: 3,
            type: "cultivo",
            requirements: { qi: 150 },
            effects: { qi: 400, mind: 1 },
            unlock_flags: ["canBuyPills"],
            unlocks: ["refine_awakening_pill"],
            repeatable: true,
            ui_reward_summary: "Aprimora sua base alquímica e libera Pílulas da Fundação.",
            log: "Sua bolsa se enche de ervas e sua cabeça se enche de possibilidades alquímicas."
        },
        watch_stars: {
            id: "watch_stars",
            name: "Observar as Estrelas",
            desc: "O céu parece desorganizado até começar a responder de volta.",
            time_cost: 4,
            type: "cultivo",
            requirements: { mind: 14 },
            effects: { mind: 2, qi: 200 },
            unlocks: ["silent_retreat"],
            repeatable: true,
            log: "Você aprende a chamar de destino o que antes parecia apenas vazio."
        },
        sect_recruiter: {
            id: "sect_recruiter",
            name: "Falar com o Recrutador da Seita",
            desc: "Ele mede seu talento, sua postura e o quanto você parece descartável.",
            time_cost: 3,
            type: "social",
            requirements: { mind: 11 },
            effects: { mind: 1 },
            unlock_flags: ["canSelectStance", "canJoinSect"],
            unlocks: ["outer_disciple_trial"],
            repeatable: false,
            ui_reward_summary: "Desbloqueia Posturas e a camada social da Seita.",
            log: "Você recebe um olhar avaliativo. Não é respeito, mas já é melhor que nada."
        },
        hunt_wild_boar: {
            id: "hunt_wild_boar",
            name: "Caçar Javali Espiritual",
            desc: "A fera corre, você corre atrás e ambos aprendem sobre violência.",
            time_cost: 3,
            type: "corpo",
            requirements: { body: 13 },
            effects: { body: 2, qi: 300 },
            unlocks: ["fight_beast"],
            repeatable: true,
            cooldownYears: 12,
            ui_reward_summary: "Rende um salto físico inicial, mas o vale logo fica sem presas úteis.",
            log: "A caçada deixa seus músculos duros e seus meridianos levemente mais ricos."
        },
        forbidden_whisper: {
            id: "forbidden_whisper",
            name: "Escutar o Sussurro Proibido",
            desc: "A voz promete atalhos. Vozes assim quase nunca mentem sobre o preço.",
            time_cost: 4,
            type: "risco",
            requirements: { mind: 12, karma_max: 5 },
            effects: { mind: 2, karma: -3 },
            unlocks: ["demonic_art"],
            repeatable: false,
            log: "Seu coração aprende uma sílaba que não deveria existir."
        },
        outer_disciple_trial: {
            id: "outer_disciple_trial",
            name: "Passar no Teste de Discípulo Externo",
            desc: "Golpes, exames e humilhação. Um processo seletivo clássico.",
            time_cost: 4,
            type: "social",
            requirements: { body: 12, mind: 12 },
            effects: { body: 1, mind: 1, qi: 300 },
            unlock_flags: ["canBuyDisciples"],
            unlocks: ["choose_orthodox_sect", "hall_of_scripts"],
            repeatable: false,
            ui_reward_summary: "Libera Discípulos como nova camada produtiva.",
            log: "Você entra pelos portões da seita. O luxo ainda não, a servidão imediatamente."
        },
        study_alchemy: {
            id: "study_alchemy",
            name: "Estudar Alquimia Básica",
            desc: "O caldeirão responde bem a quem aceita errar sem explodir a sobrancelha.",
            time_cost: 5,
            type: "cultivo",
            requirements: { mind: 15, qi: 2000 },
            effects: { mind: 3, qi: 500 },
            unlocks: ["refine_awakening_pill", "feel_heavens"],
            repeatable: false,
            log: "Pela primeira vez, sua mente organiza o caos em fórmula."
        },
        fight_beast: {
            id: "fight_beast",
            name: "Caçar Fera Espiritual",
            desc: "Lutar contra monstros é um jeito excelente de melhorar ou morrer tentando.",
            time_cost: 4,
            type: "corpo",
            requirements: { body: 16 },
            effects: { body: 3, qi: 2500 },
            unlocks: ["blood_bath", "feel_heavens"],
            repeatable: true,
            cooldownYears: 20,
            ui_reward_summary: "Cada fera abatida acelera o corpo, mas a região logo se esgota.",
            log: "A fera cai. Seu corpo aprende com a brutalidade antes da sua mente reclamar."
        },
        silent_retreat: {
            id: "silent_retreat",
            name: "Retiro do Silêncio",
            desc: "Você abandona distrações, pessoas e a noção saudável de conforto.",
            time_cost: 5,
            type: "cultivo",
            requirements: { mind: 18, qi: 3000 },
            effects: { mind: 3 },
            set_route: "void",
            blocks: ["blood_bath", "refine_awakening_pill", "choose_orthodox_sect", "soul_bargain"],
            unlocks: ["feel_heavens", "void_insight"],
            repeatable: false,
            log: "Você escolhe o vazio. Todo o resto passa a soar barulhento demais."
        },
        refine_awakening_pill: {
            id: "refine_awakening_pill",
            name: "Refinar Pílula do Despertar",
            desc: "Uma única pílula para abrir a mente ou cozinhar seu futuro em fogo alto.",
            time_cost: 6,
            type: "cultivo",
            requirements: { mind: 18, qi: 6000 },
            effects: { mind: 4, body: 1 },
            set_route: "alchemy",
            blocks: ["blood_bath", "silent_retreat", "choose_orthodox_sect", "soul_bargain"],
            unlocks: ["open_medicine_hall", "feel_heavens"],
            repeatable: false,
            log: "Seu espírito se alonga como metal em brasa. O caminho da fornalha foi escolhido."
        },
        choose_orthodox_sect: {
            id: "choose_orthodox_sect",
            name: "Jurar Lealdade à Seita Ortodoxa",
            desc: "Disciplina, hierarquia e centenas de pessoas querendo usar seu talento.",
            time_cost: 5,
            type: "social",
            requirements: { mind: 14, qi: 4000 },
            effects: { body: 2, mind: 2 },
            set_route: "sect",
            blocks: ["blood_bath", "silent_retreat", "refine_awakening_pill", "soul_bargain", "demonic_art"],
            unlocks: ["sect_duties", "hall_of_scripts", "feel_heavens"],
            repeatable: false,
            log: "Você veste o manto da seita. Agora seu talento pertence a uma máquina maior."
        },
        blood_bath: {
            id: "blood_bath",
            name: "Banho de Sangue da Fera",
            desc: "Você mergulha no sangue espiritual. Seu corpo aprova, sua expectativa de vida protesta.",
            time_cost: 6,
            type: "risco",
            requirements: { body: 22, qi: 2500 },
            effects: { body: 6, lifespan_penalty: 6 },
            set_route: "body",
            blocks: ["refine_awakening_pill", "silent_retreat", "choose_orthodox_sect", "soul_bargain"],
            unlocks: ["bone_tempering", "feel_heavens"],
            repeatable: false,
            log: "Seus ossos se racham e renascem. Você escolheu a estrada que responde com cicatrizes."
        },
        demonic_art: {
            id: "demonic_art",
            name: "Praticar Arte Demoníaca Menor",
            desc: "Roubar Qi do que deveria permanecer quieto é eficiente e repugnante.",
            time_cost: 4,
            type: "risco",
            requirements: { qi: 3000, karma_max: 0 },
            effects: { qi: 8000, body: 1, lifespan_penalty: 5, karma: -5 },
            unlocks: ["soul_bargain"],
            repeatable: true,
            cooldownYears: 30,
            ui_reward_summary: "Explode seu poder por pouco tempo, mas o preço e a fonte se tornam instáveis.",
            log: "O ganho é embriagante. O cheiro da sua alma, menos."
        },
        feel_heavens: {
            id: "feel_heavens",
            name: "Forçar a Atenção dos Céus",
            desc: "Você cutuca o firmamento até ele resolver responder com trovões.",
            time_cost: 4,
            type: "risco",
            requirements: { qi: 1800, body: 18, subRealm: 4 },
            effects: { mind: 2 },
            unlocks: [],
            repeatable: false,
            ui_reward_summary: "Prepara o espírito para a Tribulação e reforça sua leitura dos céus.",
            log: "As nuvens escurecem. Você compreende melhor a fúria dos céus antes do desafio final."
        },
        sect_duties: {
            id: "sect_duties",
            name: "Cumprir Deveres da Seita",
            desc: "Entrega de recados, escolta, cópias de manuscritos e pequenas oportunidades roubadas do sistema.",
            time_cost: 4,
            type: "social",
            requirements: { realm: 2, qi: 6000 },
            effects: { qi: 9000, mind: 1 },
            unlocks: ["formation_lessons"],
            repeatable: true,
            log: "Seu nome sobe um degrau invisível na fila de servos promissores."
        },
        hall_of_scripts: {
            id: "hall_of_scripts",
            name: "Frequentar o Salão dos Pergaminhos",
            desc: "A maioria dos discípulos dorme aqui. Você, por sorte, só perde a sanidade lentamente.",
            time_cost: 5,
            type: "social",
            requirements: { realm: 2, mind: 18, qi: 8000 },
            effects: { mind: 2, qi: 12000 },
            unlocks: ["formation_lessons"],
            repeatable: true,
            log: "Você aprende a pensar com rigor suficiente para sobreviver a bibliotecas cultivadoras."
        },
        bone_tempering: {
            id: "bone_tempering",
            name: "Tempero dos Ossos de Ferro",
            desc: "Cada ciclo de Qi atravessa a medula como um juramento martelado.",
            time_cost: 5,
            type: "corpo",
            requirements: { realm: 2, body: 26, qi: 12000 },
            effects: { body: 4, qi: 14000 },
            unlocks: ["mountain_trial", "iron_body_breakthrough"],
            repeatable: true,
            log: "Seus ossos agora rangem com autoridade."
        },
        open_medicine_hall: {
            id: "open_medicine_hall",
            name: "Abrir o Pavilhão de Medicina",
            desc: "Doenças, ferimentos e cultivadores desesperados pagam muito bem.",
            time_cost: 5,
            type: "cultivo",
            requirements: { realm: 2, mind: 20, qi: 12000 },
            effects: { qi: 18000, mind: 1 },
            unlocks: ["stabilize_foundation", "golden_cauldron_ritual"],
            repeatable: true,
            log: "Seu nome circula entre mercadores, pacientes e gente sem escrúpulos."
        },
        soul_bargain: {
            id: "soul_bargain",
            name: "Selar um Pacto da Alma",
            desc: "Poder rápido, juros eternos.",
            time_cost: 6,
            type: "risco",
            requirements: { realm: 2, qi: 10000, karma_max: -5 },
            effects: { body: 2, mind: 2, karma: -8 },
            set_route: "demonic",
            blocks: ["choose_orthodox_sect", "silent_retreat", "refine_awakening_pill", "blood_bath"],
            unlocks: ["consume_enemy_core", "black_meridian_breakthrough"],
            repeatable: false,
            log: "Você assina sem tinta. Seu destino agora sabe exatamente onde mora."
        },
        void_insight: {
            id: "void_insight",
            name: "Contemplar o Vazio Entre as Estrelas",
            desc: "Você aprende mais olhando para o nada do que muita gente olhando para mestres.",
            time_cost: 6,
            type: "cultivo",
            requirements: { realm: 2, mind: 26, qi: 50000 },
            effects: { qi: 16000, mind: 4 },
            unlocks: ["nameless_breakthrough"],
            repeatable: true,
            log: "Seu pensamento para de pedir permissão ao mundo."
        },
        formation_lessons: {
            id: "formation_lessons",
            name: "Estudar Formações Espirituais",
            desc: "Você aprende a convencer o terreno a obedecer instruções escritas em Qi.",
            time_cost: 6,
            type: "social",
            requirements: { realm: 2, mind: 20, qi: 60000 },
            effects: { qi: 26000, mind: 1 },
            unlocks: ["elder_promotion"],
            repeatable: true,
            log: "Pela primeira vez, o chão da seita trabalha a seu favor."
        },
        consume_enemy_core: {
            id: "consume_enemy_core",
            name: "Consumir Núcleo Inimigo",
            desc: "Não é elegante, mas elegância raramente vence guerras demoníacas.",
            time_cost: 5,
            type: "risco",
            requirements: { realm: 2, qi: 40000, karma_max: -5 },
            effects: { qi: 220000, body: 2, karma: -3 },
            unlocks: ["black_meridian_breakthrough"],
            repeatable: true,
            cooldownYears: 45,
            ui_reward_summary: "É um grande salto, mas você não encontra núcleos úteis para sempre.",
            log: "Seu poder cresce com a mesma velocidade da sua reputação terrível."
        },
        stabilize_foundation: {
            id: "stabilize_foundation",
            name: "Estabilizar a Fundação com Elixires",
            desc: "Você troca eficiência, paciência e alguns órgãos por estabilidade perfeita.",
            time_cost: 6,
            type: "cultivo",
            requirements: { realm: 2, mind: 24, qi: 50000 },
            effects: { mind: 2, body: 2 },
            unlocks: ["golden_cauldron_ritual", "pill_saint_ascension"],
            repeatable: false,
            log: "Sua base espiritual ganha firmeza suficiente para sustentar ambições caras."
        },
        mountain_trial: {
            id: "mountain_trial",
            name: "Provação da Montanha de Ferro",
            desc: "A montanha testa quem é duro. A gravidade também.",
            time_cost: 8,
            type: "corpo",
            requirements: { realm: 2, body: 28, qi: 55000 },
            effects: { body: 5, qi: 120000 },
            unlocks: ["iron_body_breakthrough", "beast_king_gate"],
            repeatable: false,
            log: "Pedra, peso e dor se dobram um pouco mais ao seu passo."
        },
        elder_promotion: {
            id: "elder_promotion",
            name: "Disputar Promoção a Ancião",
            desc: "Na seita, respeito é só outro nome para poder administrativo.",
            time_cost: 8,
            type: "social",
            requirements: { realm: 3, mind: 24, qi: 500000, disciples: 18 },
            effects: { qi: 450000, body: 2 },
            unlock_flags: ["canBuyElders", "canBuyArrays"],
            unlocks: ["found_own_peak"],
            repeatable: false,
            ui_reward_summary: "Libera Anciões e Matrizes de Convergência para fechar a rota da seita.",
            log: "Você ganha assento, autoridade e alunos suficientes para não dormir mais em paz."
        },
        golden_cauldron_ritual: {
            id: "golden_cauldron_ritual",
            name: "Ritual do Caldeirão Dourado",
            desc: "A chama alquímica sobe como um sol doméstico e arrogante.",
            time_cost: 8,
            type: "cultivo",
            requirements: { realm: 3, mind: 28, qi: 350000 },
            effects: { qi: 500000, mind: 5 },
            unlocks: ["pill_saint_ascension"],
            repeatable: false,
            log: "Seu caldeirão finalmente para de ser ferramenta e vira extensão da sua vontade."
        },
        nameless_breakthrough: {
            id: "nameless_breakthrough",
            name: "Romper sem Dar Nome ao Dao",
            desc: "Você avança sem fundar escola, sem pedir testemunhas e sem explicar nada.",
            time_cost: 8,
            type: "cultivo",
            requirements: { realm: 3, mind: 32, qi: 450000 },
            effects: { qi: 450000, mind: 5 },
            unlocks: ["walk_beyond_mortals"],
            repeatable: false,
            log: "O seu avanço não cabe em doutrina. Isso o torna mais perigoso e muito mais solitário."
        },
        black_meridian_breakthrough: {
            id: "black_meridian_breakthrough",
            name: "Ruptura dos Meridianos Negros",
            desc: "Você força o impossível até o impossível ceder por medo.",
            time_cost: 8,
            type: "risco",
            requirements: { realm: 3, body: 22, qi: 420000, karma_max: -12 },
            effects: { qi: 650000, body: 4, mind: 4 },
            unlocks: ["karma_storm"],
            repeatable: false,
            log: "Seus canais espirituais escurecem como um juramento de guerra."
        },
        iron_body_breakthrough: {
            id: "iron_body_breakthrough",
            name: "Ruptura do Corpo de Ferro",
            desc: "Sua carne para de pedir licença à dor.",
            time_cost: 8,
            type: "corpo",
            requirements: { realm: 3, body: 34, qi: 500000 },
            effects: { qi: 500000, body: 8 },
            unlocks: ["beast_king_gate"],
            repeatable: false,
            log: "Seu corpo cruza um limite que a maioria só descreve com reverência ou terror."
        },
        karma_storm: {
            id: "karma_storm",
            name: "Convocar a Tempestade Cármica",
            desc: "Os céus já o odeiam. Você decide transformar isso em combustível.",
            time_cost: 10,
            type: "risco",
            requirements: { realm: 4, qi: 9000000, karma_max: -20 },
            effects: { karma: -10, qi: 3000000 },
            unlocks: ["ten_thousand_ghosts_rite"],
            repeatable: false,
            log: "Trovões negros respondem ao seu nome. O resto do mundo prefere não comentar."
        },
        pill_saint_ascension: {
            id: "pill_saint_ascension",
            name: "Ascensão do Santo das Pílulas",
            desc: "Você fecha o ciclo da longevidade num único grande refinamento.",
            time_cost: 12,
            type: "cultivo",
            requirements: { realm: 4, mind: 38, qi: 5000000, pills: 150 },
            effects: { qi: 10000000, mind: 6 },
            ending: {
                title: "Santo da Fornalha Dourada",
                text: "Seu nome atravessa gerações em frascos selados. Você não vence o tempo; você o destila."
            },
            repeatable: false,
            log: "O caldeirão dourado se fecha. Quando a tampa abre, uma lenda sai respirando."
        },
        found_own_peak: {
            id: "found_own_peak",
            name: "Fundar Seu Próprio Pico",
            desc: "Você deixa de servir uma seita e passa a ser a seita que outros temem servir.",
            time_cost: 12,
            type: "social",
            requirements: { realm: 4, qi: 8000000, elders: 20, arrays: 5 },
            effects: { qi: 12000000, body: 4, mind: 4 },
            ending: {
                title: "Patriarca do Pico Celestial",
                text: "Seu nome vira selo, ordem e tradição. O mundo o chama de mestre porque precisa de um."
            },
            repeatable: false,
            log: "Um novo pico se ergue sob sua vontade. Discípulos passam a recitar seu nome como lei."
        },
        walk_beyond_mortals: {
            id: "walk_beyond_mortals",
            name: "Caminhar Além dos Mortais",
            desc: "Você abandona até a vontade de ser lembrado.",
            time_cost: 12,
            type: "cultivo",
            requirements: { realm: 4, mind: 42, qi: 6000000 },
            effects: { qi: 9000000, mind: 6 },
            ending: {
                title: "Sábio Sem Nome do Vazio",
                text: "Você some do mapa e cresce dentro do céu. O mundo só percebe depois que já era tarde."
            },
            repeatable: false,
            log: "Você dá um passo tão silencioso que o próprio mundo demora a notar que foi ultrapassado."
        },
        beast_king_gate: {
            id: "beast_king_gate",
            name: "Abrir o Portão do Rei das Feras",
            desc: "Você testa se a montanha consegue suportar a criatura que se tornou.",
            time_cost: 12,
            type: "corpo",
            requirements: { realm: 4, body: 44, qi: 7000000 },
            effects: { qi: 11000000, body: 10 },
            ending: {
                title: "Rei das Feras da Montanha",
                text: "Você deixa de ser homem ou fera. Nas fronteiras, ambas as palavras passam a significar você."
            },
            repeatable: false,
            log: "A montanha treme. Não de medo do céu, mas de respeito por aquilo que agora a habita."
        },
        ten_thousand_ghosts_rite: {
            id: "ten_thousand_ghosts_rite",
            name: "Rito dos Dez Mil Fantasmas",
            desc: "O céu recua um passo. O inferno avança dois.",
            time_cost: 12,
            type: "risco",
            requirements: { realm: 4, body: 30, mind: 30, qi: 15000000, karma_max: -25 },
            effects: { qi: 20000000, karma: -20 },
            ending: {
                title: "Trono da Calamidade Rubra",
                text: "Você não ascende apesar da corrupção, mas por causa dela. Seu nome sobrevive como maldição e oração."
            },
            repeatable: false,
            log: "Dez mil ecos obedecem. Os vivos se ajoelham porque a alternativa é mais barulhenta."
        }
    }
};

const JOURNEY_GRAPH_LAYOUT = {
    work_farm: { x: 120, y: 120, lane: "mortal" },
    hear_legends: { x: 120, y: 260, lane: "mortal" },
    village_elder: { x: 120, y: 400, lane: "mortal" },
    rest_under_tree: { x: 120, y: 540, lane: "mortal" },
    explore_forest: { x: 380, y: 120, lane: "mortal" },
    breathe: { x: 380, y: 260, lane: "mortal" },
    find_cave: { x: 380, y: 400, lane: "mortal" },
    explore_ruins: { x: 380, y: 680, lane: "mortal" },
    hunt_wild_boar: { x: 640, y: 120, lane: "despertar" },
    read_scroll: { x: 640, y: 340, lane: "despertar" },
    gather_spirit_herbs: { x: 640, y: 440, lane: "despertar" },
    watch_stars: { x: 640, y: 560, lane: "despertar" },
    sect_recruiter: { x: 640, y: 760, lane: "despertar" },
    forbidden_whisper: { x: 640, y: 900, lane: "despertar" },
    fight_beast: { x: 920, y: 120, lane: "especializacao" },
    study_alchemy: { x: 920, y: 340, lane: "especializacao" },
    silent_retreat: { x: 920, y: 560, lane: "especializacao" },
    outer_disciple_trial: { x: 920, y: 760, lane: "especializacao" },
    demonic_art: { x: 920, y: 900, lane: "especializacao" },
    blood_bath: { x: 1200, y: 120, lane: "rota" },
    refine_awakening_pill: { x: 1200, y: 340, lane: "rota" },
    feel_heavens: { x: 1200, y: 520, lane: "gargalo" },
    choose_orthodox_sect: { x: 1200, y: 760, lane: "rota" },
    soul_bargain: { x: 1200, y: 900, lane: "rota" },
    bone_tempering: { x: 1480, y: 120, lane: "condensacao" },
    open_medicine_hall: { x: 1480, y: 340, lane: "condensacao" },
    void_insight: { x: 1480, y: 560, lane: "condensacao" },
    sect_duties: { x: 1480, y: 700, lane: "condensacao" },
    hall_of_scripts: { x: 1480, y: 820, lane: "condensacao" },
    consume_enemy_core: { x: 1480, y: 960, lane: "condensacao" },
    mountain_trial: { x: 1760, y: 120, lane: "fundacao" },
    stabilize_foundation: { x: 1760, y: 340, lane: "fundacao" },
    formation_lessons: { x: 1760, y: 760, lane: "fundacao" },
    iron_body_breakthrough: { x: 2040, y: 120, lane: "fundacao" },
    golden_cauldron_ritual: { x: 2040, y: 340, lane: "fundacao" },
    nameless_breakthrough: { x: 2040, y: 560, lane: "fundacao" },
    elder_promotion: { x: 2040, y: 760, lane: "fundacao" },
    black_meridian_breakthrough: { x: 2040, y: 960, lane: "fundacao" },
    beast_king_gate: { x: 2320, y: 120, lane: "final" },
    pill_saint_ascension: { x: 2320, y: 340, lane: "final" },
    walk_beyond_mortals: { x: 2320, y: 560, lane: "final" },
    found_own_peak: { x: 2320, y: 760, lane: "final" },
    karma_storm: { x: 2320, y: 960, lane: "final" },
    ten_thousand_ghosts_rite: { x: 2600, y: 960, lane: "final" }
};

Object.entries(JOURNEY_GRAPH_LAYOUT).forEach(([actionId, graph]) => {
    if (GAME_DATA.journeyActions[actionId]) {
        GAME_DATA.journeyActions[actionId].graph = graph;
    }
});
